### ISSUE TITLE
Clarify Stretch Hint for cityreader.py

### ISSUE THREAD

**Issue by snowcoding** [LambdaSchool/Sprint-Challenge--Intro-Python#112]
I think this was a cool stretch problem. Let's take a look at the description:
```
# *** STRETCH GOAL! ***
#
# Allow the user to input two points, each specified by latitude and longitude.
# These points form the corners of a lat/lon square. Output the cities that fall
# within this square.
#
# Be aware that the user could specify either a lower-left/upper-right pair of
# coordinates, or an upper-left/lower-right pair of coordinates. Hint: normalize
# the input data so that it's always one or the other, then search for cities.
```

Given Brady's and Beej's solution today, I believe the hint of : "... normalize the input data so that it's always one or the other, then search", may be slightly clearer if stated as: "... allow the user to enter either pair of coordinates, then figure out which pair it is, then search.

Thanks!

**Comment by br80** [comment]
Updated wording to clarify a bit more.
